sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: pOoyiHIbXysJ2xIU7qMbQXuZEsCYCGo5eWqOaCt87DK1gRN8plBeHK+y3uv/k0QFirVCa2R/BzmF2lvna0k2bC8s1AMBwFS+oHTX/IkBpX1PVNIVO+n3yLJH73JpmDU3yLxRcS0Xv3qtxBAouT+J9yGkr80D8QPFDUQ7gaAkM4L7Fidsk3AvkTWSuHZXFA3SXEZ4WQVetxNGVeYhKod1fg22Sk9oUYk9hRj+kZrL4i28s57YN+cZzd+Jg0rPC/6rnwhtt8X6e7cWiJXearBTV14aIzBqjeAV4cvJZXL2IBe6JjSGlbzgvjwapgctBzmWOC86kjpzG9VpCEYcnqhPgZmbXWGZVzSdeqyRVIqoXHuZNRdcYiXa3DzohcVRfgSonWkKuaagQHqAQv+xBgXKyL5bH2GVlOUStnLmuYK00Xopy6E8J3ztdhiFNMov7rrbSY97oAUqn1JIKROVG5tfb37ZLWqXOUhjJx5ZojdVDTHjMY161RhXvz69chF6twXKJhL3nLsB1nwcywv1UEey66kDZtn/A5Oi7/fUGLPx9JyrT6AboYCmKfU43pk8qpSXjsfIQ3YOarySIIJg0M2UV67r559US/RHAuuFCRQx4Lsf4Spm4NoFgqxdePjUrfb8uCVRA0ofp2T4WQSj0WbflmPWaPPCNZIJUr2koMajauw=
  - secure: KtBbBTzAU2HlTb4DQe/Axa0f+1cb7ojTvBm75g8pdRBeaJfhdyOo9jca/ioYyb+yE4FE4Hel4ghDWZ78P5Dorn00fnAVbDMJqzvkGzZj7FZcIAJ13v5usj3FOeoVE9pbHBtOlXLknDx3cGK/RdsCktA68BgH6b8A7lVqR2y2KyDu97gGGxbNDCeMRezD2AEa4BpYAvYYHczTlC6ZCWVIGHTIP4tvWyPNF4RvkqS4BUhSPfoYT6TeJEi1k0DHWODEDGAEdJI8sdeSgs7465PwQRJdB4g2V0byi1LPaq4j97QGkzrMaKOkwli0CedDemUF7Lxl2ujiY2dMj1trFlDTOXUA9WNU1BfY9oGyiBD7FUBikPQgF5/pPBPvx2INwE/dBhQUVqiSlRsMRnr7oR7TWQHbVq1PF97tbMukDkm33G3ZbHjUBuZOT6+2kKYODdin/UT9yWbxAqDj1CnL/kkqN+jrUoKvRgtSL5igCKmgWRU//cagUj/dmz1Jh5FI67CcB0Ktsp9Os+m+66f1I+QgT6UXhm3afI+J77YcJUQjC6+OszwXvGVzfgpWVsmb2m6EVwyLV+MNpVUz321Q3SZ0ChUYDW9+GPxNBbmlcF9cOsxcUjcBb1sQYhkdUq4UmWB9jsmlWhF8+Rr2rE4QAv/rAmloARQovlol75/KOFxGYDM=
